FROM --platform=$BUILDPLATFORM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY go.mod *.go *.sum ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /gen

FROM alpine:latest
WORKDIR /
COPY --from=builder /gen /gen
EXPOSE 8080
ENTRYPOINT ["/gen"]
