// <auto-generated />
using System;
using ECommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerce.App.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260329071324_new_mig")]
    partial class new_mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Data.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneE164")
                        .HasColumnType("text")
                        .HasColumnName("phone_e164");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("users_phone_e164_key");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Brand", b =>
                {
                    b.Property<Guid>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("BrandId")
                        .HasName("brands_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("brands_name_key");

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("CategoryId")
                        .HasName("categories_pkey");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("categories_slug_key");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("AttrsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("attrs");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SkuBase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku_base");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ProductId")
                        .HasName("products_pkey");

                    b.HasIndex("AttrsJson")
                        .HasDatabaseName("idx_products_attrs_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AttrsJson"), "gin");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_products_active")
                        .HasFilter("(status = 'active')");

                    b.ToTable("products", "catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.ProductMedia", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("MediaId")
                        .HasName("product_media_pkey");

                    b.HasIndex("ProductId", "Kind", "SortOrder")
                        .HasDatabaseName("idx_media_product_kind_sort");

                    b.ToTable("product_media", "catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Variant", b =>
                {
                    b.Property<Guid>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<int[]>("DimensionsMm")
                        .HasColumnType("integer[]")
                        .HasColumnName("dimensions_mm");

                    b.Property<string>("OptionKvJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("option_kv");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int?>("WeightG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_g");

                    b.HasKey("VariantId")
                        .HasName("variants_pkey");

                    b.HasIndex("OptionKvJson")
                        .HasDatabaseName("idx_variants_optionkv_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OptionKvJson"), "gin");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("variants_sku_key");

                    b.ToTable("variants", "catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Crm.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("AddressId")
                        .HasName("addresses_pkey");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_addresses_default_one")
                        .HasFilter("is_default");

                    b.ToTable("addresses", "crm");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Crm.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CustomerId")
                        .HasName("customers_pkey");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("customers_user_id_key");

                    b.ToTable("customers", "crm");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.StockItem", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<int>("QtyOnHand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("qty_on_hand");

                    b.Property<int>("QtyReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("qty_reserved");

                    b.HasKey("WarehouseId", "VariantId")
                        .HasName("stock_items_pkey");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_stock_items_variant");

                    b.ToTable("stock_items", "inventory");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.Warehouse", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("WarehouseId")
                        .HasName("warehouses_pkey");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("warehouses_code_key");

                    b.ToTable("warehouses", "inventory");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Pricing.Price", b =>
                {
                    b.Property<Guid>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("PriceId")
                        .HasName("prices_pkey");

                    b.HasIndex("PriceListId");

                    b.HasIndex("VariantId", "PriceListId", "ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("idx_prices_lookup");

                    b.ToTable("prices", "pricing");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Pricing.PriceList", b =>
                {
                    b.Property<Guid>("PriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("PriceListId")
                        .HasName("price_lists_pkey");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("price_lists_code_key");

                    b.ToTable("price_lists", "pricing");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Sales.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CartId")
                        .HasName("carts_pkey");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_carts_customer");

                    b.ToTable("carts", "sales");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Sales.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cart_item_id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_snapshot");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("CartItemId")
                        .HasName("cart_items_pkey");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("idx_cart_items_variant");

                    b.HasIndex("CartId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("cart_items_cart_id_variant_id_key");

                    b.ToTable("cart_items", "sales");
                });

            modelBuilder.Entity("ECommerce.Data.LatestPriceDto", b =>
                {
                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceListCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ECommerce.Data.PriceRankWithinCategoryDto", b =>
                {
                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("PriceRankInCategory")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ECommerce.Data.RunningCartValueDto", b =>
                {
                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RunningTotalByCustomer")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Category", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Catalog.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("categories_parent_id_fkey");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Product", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Catalog.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("products_brand_id_fkey");

                    b.HasOne("ECommerce.Data.Entities.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("products_category_id_fkey");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.ProductMedia", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Catalog.Product", "Product")
                        .WithMany("Media")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_media_product_id_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Variant", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Catalog.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("variants_product_id_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Crm.Address", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Crm.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("addresses_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Crm.Customer", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Auth.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("ECommerce.Data.Entities.Crm.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("customers_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.StockItem", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Catalog.Variant", "Variant")
                        .WithMany("StockItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("stock_items_variant_id_fkey");

                    b.HasOne("ECommerce.Data.Entities.Inventory.Warehouse", "Warehouse")
                        .WithMany("StockItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("stock_items_warehouse_id_fkey");

                    b.Navigation("Variant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Pricing.Price", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Pricing.PriceList", "PriceList")
                        .WithMany("Prices")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prices_price_list_id_fkey");

                    b.HasOne("ECommerce.Data.Entities.Catalog.Variant", "Variant")
                        .WithMany("Prices")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("prices_variant_id_fkey");

                    b.Navigation("PriceList");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Sales.Cart", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Crm.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("carts_customer_id_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Sales.CartItem", b =>
                {
                    b.HasOne("ECommerce.Data.Entities.Sales.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cart_items_cart_id_fkey");

                    b.HasOne("ECommerce.Data.Entities.Catalog.Variant", "Variant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cart_items_variant_id_fkey");

                    b.Navigation("Cart");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Auth.User", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Product", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Catalog.Variant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Prices");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Crm.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Carts");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Inventory.Warehouse", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Pricing.PriceList", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("ECommerce.Data.Entities.Sales.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
